### ISSUE TITLE
To-fix stops working for one minute

### ISSUE THREAD

**Issue by kupendrayadav** [osmlab/to-fix-backend#105]
While working on to-fix from last few days, we came across an interesting thing that happened twice in every day. The to-fix used to stop working for one minute with an error message as `something went wrong`. It used to fix automatically after reloading the page for few times. Also checked with the @mapsquad on this, where they also faced the same issue. Couldn't able to take a screen shot. But still able to provide that soon, if we face the same issue again.

cc @Rub21

**Comment by kupendrayadav** [comment]
![something](https://user-images.githubusercontent.com/20293098/28256550-32cbcdcc-6ae1-11e7-8ad6-aa31740d24c5.jpg)

**Comment by kepta** [comment]
Closing this in favour of the  postgis rewrite #113
