### ISSUE TITLE
Setting up locally.

### ISSUE THREAD

**Issue by geohacker** [osmlab/to-fix-backend#108]
@Rub21 could you outline steps for setting up the backend locally? I've the following:

* install elastic search
* create an index `http://localhost:9200/tofix?pretty`

Questions:

* How does one create a user? What are the attributes needed? 
* I see a sample task in test/ but not sure if this is correct? 

Thank you! 

cc @batpad @ajithranka

**Comment by Rub21** [comment]
> How does one create a user? What are the attributes needed?
 
The first session in to-fix-backend creates a user with superadmin role, you don't need any parameters in the  to create it, only login with OSM and the greater the perception 

![image](https://user-images.githubusercontent.com/1152236/29721481-03366a02-8983-11e7-87b7-3e49e716d426.png)

> I see a sample task in test/ but not sure if this is correct?

 To create a task you can use: https://github.com/Rub21/tofix-cli 👇   but you ahve to import first your token 


```
$ export token=eyJhbGc.... 
$ tfcli dev create --name 'test' --comment 'abc' --description 'abc' --file out.geojson 

```

**Comment by kepta** [comment]
Closing this in favour of the  postgis rewrite #113
