### ISSUE TITLE
Query activity data by date

### ISSUE THREAD

**Issue by tristen** [osmlab/to-fix-backend#11]
For an endpoint like `/track/{taskName}/{key}:{value}`

An example query would look like `/track/unconnectedmajor/from:2015-03-17` which returning an array of objects of user activity of that particular task.

A query like `/track/unconnectedmajor/from:2015-03-17/to:2015-03-19` would return an array of objects of user activity of a particular task between the dates March 17th - 19th.

**Comment by aaronlidman** [comment]
Added in https://github.com/osmlab/to-fix-backend/commit/43ea307d0f0149e9e1d73e75335fe56e4d7802d8.

For example: http://54.147.184.23:8000/track/unconnectedmajor/from:2015-03-18/to:2015-03-21

**Comment by tristen** [comment]
Can you document this in [API](https://github.com/osmlab/to-fix-backend/blob/master/API.md)?
