### ISSUE TITLE
Failing with big requests

### ISSUE THREAD

**Issue by kepta** [osmlab/to-fix-backend#129]
Tofix fails when you bombard the `put task/:tid/item/:id`  with >1 simultaneous requests.
It works fine with delayed request (added a test for this also).

The error seems to show 
```
 sql: INSERT INTO "task_user_stats" ("user","task_id","stats","createdAt","updatedAt") VALUES ('undefined','one','{"2017-10-12":{"completed":-1,"fixed":0,"noterror":0,"open":0,"undefined":null}}','2017-10-12 14:12:53.128 +00:00','2017-10-12 14:12:53.128 +00:00') RETURNING *;
```
Looks like user becomes `undefined` for simultaneous requests. 

With further investigations the [was.user](https://github.com/osmlab/to-fix-backend/blob/postgis/lib/put-item.js#L91) becomes`undefined`.

Next steps
- [x] Create a [test case](https://github.com/osmlab/to-fix-backend/pull/128/files#diff-3ce36960f0ea85c9572ab7c6ff0a6f78R467)  to test this.
- [ ] Figure out why `was.user` becomes undefined for certain requests.

cc @mcwhittemore @batpad

**Comment by kepta** [comment]
cc @coxchapman

**Comment by batpad** [comment]
@kepta we good to close this?

**Comment by kepta** [comment]
Yes, closing it.
