### ISSUE TITLE
Trouble running tests locally

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#130]
👋  I'm a postgres newbie, and I'm having trouble running tests locally.  I hit an error at this test:
https://github.com/osmlab/to-fix-backend/blob/0549579366178ea72da7a3d39f83cf7b8ea4432c/test/task-items.test.js#L303

The error is:
`[Sat, 14 Oct 2017 00:43:56 GMT] [error] [default] TypeError: Cannot read property 'gt' of undefined`

In server.js, the `Op` variable ends up undefined. I assume the problem here is some configuration step that I'm missing or that I've done wrong.

**Comment by emilymdubois** [comment]
Closed via https://github.com/osmlab/to-fix-backend/pull/137
