### ISSUE TITLE
Create Tags endpoints

### ISSUE THREAD

**Issue by emilymdubois** [osmlab/to-fix-backend#140]
Here are the endpoints I think we'll need for project and item tags with the available query and parameter options. One thing that I'm navigating is when to use the following:
- **Tag ID**: an autogenerated integer assigned when the label is created
- **Tag name**: a user-friendly title provided by by the label creator

Below, all instances of `:tag` can be assumed to mean tag ID, and all instances of `tag` can be assumed to mean tag name. Would love thoughts from other stakeholders!

@batpad @kepta @samanpwbb 

---

## Get all tags for project
```sh
GET /project/:project/tags
```
#### Query parameters
Name | Type | Description
---|---|---
`tag` | string | **Optional.** May be passed to filter returned tags where tag name contains the provided string.

## Create a project tag
```sh
POST /project/:project/tags
```
#### Payload parameters
Name | Type | Description
---|---|---
`name` | string | **Required.** The tag name.

## Get a project tag
```sh
GET /project/:project/tags/:tag
```

## Update a project tag
```sh
PUT /project/:project/tags/:tag
```
#### Payload parameters
Name | Type | Description
---|---|---
`name` | string | **Required.** The new tag name.

## Delete a project tag
```sh
DELETE /project/:project/tags/:tag
```

## Get all tags for item
```sh
GET /project/:project/item/:item/tags
```
#### Query parameters
Name | Type | Description
---|---|---
`tag` | string | **Optional.** May be passed to filter returned tags where tag name contains the provided string.

## Add a tag to an item
```sh
POST /project/:project/item/:item/tags
```
#### Payload parameters
Name | Type | Description
---|---|---
`tagIds` | array<string> | **Required.** An array of tag IDs to add to the item.

## Delete a tag from an item
```sh
DELETE /project/:project/item/:item/tags/:tag
```

**Comment by batpad** [comment]
This is done! Let's create separate issues if there's specifics that need changing.
