### ISSUE TITLE
Create Comments endpoints

### ISSUE THREAD

**Issue by emilymdubois** [osmlab/to-fix-backend#141]
Here are the endpoints I think we'll need for item comments with the available query and parameter options. All instances of `:comment` can be assumed to mean comment ID, an autogenerated integer assigned when the comment is created.

@batpad @kepta @samanpwbb 

---

## Get all comments for an item
```sh
GET /project/:project/items/:item/comments
```

## Create a comment
```sh
POST /project/:project/items/:item/comments
```
#### Payload parameters
Name | Type | Description
---|---|---
`body` | string | **Required.** The comment text.
`coordinates` | array<number> | **Optional.** Longitude and latitude associated with the comment.

## Get a comment
```sh
GET /project/:project/items/:item/comments/:comment
```

## Update a comment
```sh
PUT /project/:project/items/:item/comments/:comment
```
#### Payload parameters
Name | Type | Description
---|---|---
`body` | string | **Optional.** The new comment text.
`coordinates` | array<number> | **Optional.** The new longitude and latitude associated with the comment. 

## Delete a comment
```sh
DELETE /project/:project/items/:item/comments/:comment
```

**Comment by batpad** [comment]
This is done! Let's create separate tickets for changes.
