### ISSUE TITLE
Add a `metadata` field to Item?

### ISSUE THREAD

**Issue by batpad** [osmlab/to-fix-backend#147]
Right now, we can associate arbitrary `properties` for individual features within a `FeatureCollection` belonging to an `Item`.

Will we have cases where we are shoe-horning these properties to Features within an Item when we actually want arbitrary JSON / properties tied to the Item itself, and not individual features?

For example - the use cases where there is a screenshot or audio file associated with the `Item` as a whole. We *could* put it as a property of one of the features inside the FeatureCollection, but it seems like it might be cleaner if we have a `metadata` field to be able to associate arbitrary JSON with the Item as a whole.

Proposal:

 - Add a `metadata` field to `Item` which is optional, that can contain arbitrary JSON. The backend does not need to do any validation of this JSON, and item creators can pass in any arbitrary JSON that would get passed through to the frontend when it requests an Item.

cc @emilymdubois @samanpwbb

**Comment by emilymdubois** [comment]
We've added this ✨ https://github.com/osmlab/to-fix-backend/blob/2902f981d4ffcb722acc4bf8c3fab28b1e288612/database/item.js#L61-L65
