### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by emilymdubois** [osmlab/to-fix-backend#152]
Seeing the following error with regard to the following lines:

```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

https://github.com/osmlab/to-fix-backend/blob/4961c276d4ba609e804494203601a4c79d2f8de5/lib/server.js#L33-L40

**Comment by batpad** [comment]
This was fixed, we now use the database as the session store backend and things look good.
