### ISSUE TITLE
add metadata to tags

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#156]
we need to be able to give tags a color value.

**Comment by emilymdubois** [comment]
Closed with https://github.com/osmlab/to-fix-backend/pull/165

**Comment by emilymdubois** [comment]
Oops, this hasn't been implemented in the application code yet, just the schema.

**Comment by batpad** [comment]
Done.

**Comment by batpad** [comment]
Oops, reopening.

**Comment by emilymdubois** [comment]
This is implemented [here](https://github.com/osmlab/to-fix-backend/blob/d1bd6ddb59e7311d2ed9ec8ef86b059cce2d748e/routes/tag.js).
