### ISSUE TITLE
get project item and tag item counts with listing endpoints

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#158]
It should be possible to build a lists like this:
<img width="133" alt="screen shot 2017-10-19 at 11 00 07 am" src="https://user-images.githubusercontent.com/108094/31786246-b349baf2-b4bc-11e7-84ac-226022f5cfe5.png">
<img width="131" alt="screen shot 2017-10-19 at 11 00 03 am" src="https://user-images.githubusercontent.com/108094/31786247-b36125f2-b4bc-11e7-946c-8ed44746f824.png">

**Comment by batpad** [comment]
We now have stats per project at `/v1/projects/:projectid/stats`. This will give you:

 - `total` issues in the project
 - `tags` - issues per tag
 - `status` - issues per status

@samanpwbb does this address the above needs?

**Comment by batpad** [comment]
@samanpwbb feel free to re-open if the `project stats` endpoint does not address this.
