### ISSUE TITLE
Should we add versioning to the API?

### ISSUE THREAD

**Issue by batpad** [osmlab/to-fix-backend#167]
It may be a good idea to prefix api end-points within something like `/api/v1/` just so that if we need to make breaking changes in the future, we can have a period of time where we keep `/api/v1/` working and create an `/api/v2/` .. I don't think we need to have fully sketched out HOW we handle multiple versions in the code, but it would at least give us an escape hatch in case we needed to make breaking changes and would let us give time for consumers to update.

The proposal here would be, for now, to simply prefix all our routes with either `/api/v1/` or just `/v1/`

cc @emilymdubois @mcwhittemore

**Comment by mcwhittemore** [comment]
There is only going to be on version right? This seems like a good idea. Always possible to add versioning later as well, but it is nicer to have it from the start.

**Comment by batpad** [comment]
We added a `/v1` prefix to all end-points!
