### ISSUE TITLE
add additional status options, add filtering by status

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#168]
the following options for `status` should exist: `"open" | "fixed" | "noterror" | "unfixable" | "fixed-verified" | "noterror-verified" | "unfixable-verified"`.  It should also be possible to filter issues by status.

**Comment by batpad** [comment]
@samanpwbb do some of those statuses correspond to an idea of the issue being `closed` and others correspond to it being still `open`? Does the backend need to care about whether statuses correspond to being open or closed?

**Comment by batpad** [comment]
Disregard my question above.

**Comment by batpad** [comment]
Dunzo
