### ISSUE TITLE
API decisions / changes before we can go live

### ISSUE THREAD

**Issue by batpad** [osmlab/to-fix-backend#172]
There's a couple of fundamental changes to the API structure that we should consider prioritizing before we go live with this, to minimize any confusion:

 - Add versioning: https://github.com/osmlab/to-fix-backend/issues/167
 - Decide whether list end-points return straight up arrays, or nested objects. For eg. does the `items` endpoint return just an array of items, or an object with like `{ 'items': [] }` - the advantage to the nested object is that it makes it easy for us to add additional properties like `count` down the line.

Both these would be breaking changes for consumers, and I strongly propose we do them sooner rather than later.

cc @emilymdubois @samanpwbb @coxchapman

**Comment by samanpwbb** [comment]
- 👍 to versioning
- I had always figured the listing endpoint would be the one that gives us the count value. But I can see how the format above is more flexible, and easier to apply consistently across endpoints, so let's make this change 👍

**Comment by emilymdubois** [comment]
So we're consistent across endpoints, I'll be implementing versioning in the tags PR as

`GET /:version/projects/:project/items/:items/tags`

where `:version` must match the `^v\d+$` RegEx pattern.

**Comment by batpad** [comment]
I feel good about this. Closing.
