### ISSUE TITLE
Do we need the `get-project` endpoint?

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#183]
I don't foresee any case where we need to request an individual project. Projects will always be fetched from their listing endpoint.

**Comment by emilymdubois** [comment]
It sounds like the individual GET endpoints will only be useful for items. Projects, tags, and comments will usually be fetched from the listing endpoint. Does that sound accurate?

**Comment by samanpwbb** [comment]
yep, that's right. i don't think there's any harm in this endpoint existing – lets revisit this post Nov-1.

**Comment by batpad** [comment]
I like the idea of keeping this end-point - it can be useful to automated scripts and other clients. And follows a RESTful pattern such that I'd expect this end-point to exist as an API consumer. If either of you feel strongly about removing it, feel free to re-open.
