### ISSUE TITLE
Support multiple tags in query parameters

### ISSUE THREAD

**Issue by emilymdubois** [osmlab/to-fix-backend#193]
Currently, we can only either fetch all tags via the listing endpoint, or an individual tag. It would be great to be able to fetch a subset of tags given a query parameter containing an array of tag UUIDs.

cc @samanpwbb @batpad

**Comment by batpad** [comment]
> It would be great to be able to fetch a subset of tags given a query parameter containing an array of tag UUIDs.

Is there a reason to use UUIDs and not just the full tag names?

**Comment by emilymdubois** [comment]
We'll have access to UUIDs on the front-end, and passing those back-end will be more reliable in the event that tag names change.

**Comment by batpad** [comment]
Cool, sounds good 👍 - I think ultimately we may want to support both / either - but starting with UUIDs sounds good (and more reliable) to me.

**Comment by batpad** [comment]
This is done!

**Comment by emilymdubois** [comment]
Amazing, thank you @batpad!
