### ISSUE TITLE
Create an `ActivityLog` table

### ISSUE THREAD

**Issue by batpad** [osmlab/to-fix-backend#207]
To support gathering statistics for tasks, let's have an `ActivityLog` table that records all user actions on items. This table will be append-only, and will not do any aggregation - just write logs of every user action that can be queried and aggregated by anyone wanting to parse and generate statistics. It will also provide us with a sort of audit log.

I think we only need to record actions on `Item`s, so here is my proposed schema:

 - `id` - auto-incrementing id for record
 - `username` - user who performed action
 - `action` - a string, representing the action performed -- eg. `locked`, `status-update`, `tag-added`, etc.
 - item_id - ForeignKey to `Item`
 - `timestamp` - Timestamp of action
 - `itemBefore` - JSON of item before action
 - `itemAfter` - JSON of item after action

^^ I'm not sure we need the full item before / after representation and hopefully we can represent changes more succinctly, but I need to think about this a bit more.

cc @coxchapman @emilymdubois @mcwhittemore

**Comment by mcwhittemore** [comment]
Is the goal here to create an audit log that needs to stay around forever, or to power a stats feature maintained as some separate project?

If its just the stats thing, than maybe we can use structured logging to achieve this and not add a ton of data to the to-fix database. @mick might have thoughts on tools for structured logging.

**Comment by batpad** [comment]
We may not want it to stay around forever in this database. The idea would be that another tool queries this table every hour (or so), does some parsing, and then writes things to a place that works with structured logging systems.

**Comment by mick** [comment]
unless we are going to do something with this table in to-fix itself, I think outputting the full stream of events to a log direct, either via stdout or optionally writing to a stream (kinesis firehose?) and letting other systems handle the aggregation would work well.

**Comment by batpad** [comment]
Per discussion, let the responsibility of this app be just to write logs out to either `stdout` or a custom function - this will give more flexibility to pipe logs elsewhere.

**Comment by batpad** [comment]
We no longer want this table as we're writing out all logs we need to a `winston` transport that transports it to an appropriate log handler.
