### ISSUE TITLE
All endpoints with from/to arguments should accept single day

### ISSUE THREAD

**Issue by tristen** [osmlab/to-fix-backend#22]
Its possible to select a single day from the graph and a query like this breaks: 
http://54.147.184.23:8000/track_stats/highwayhighway/from:2015-03-23/to:2015-03-23

cc @aaronlidman

**Comment by aaronlidman** [comment]
@tristen Fixed and deployed, http://54.147.184.23:8000/track_stats/highwayhighway/from:2015-03-23/to:2015-03-23
