### ISSUE TITLE
A way to delete projects and items

### ISSUE THREAD

**Issue by emilymdubois** [osmlab/to-fix-backend#221]
We originally decided not to create delete endpoints for projects and items because without permissions scoping, these endpoints would be exposed to any API user. However, in the development process, we've accumulated cruft in the testing database that does not adhere to the database schema, which may create bugs on the front-end. The most pronounced problem is features with item collections that were imported before GeoJSON validation on the back-end that have reversed latitude and longitude values.

**Short-term solution:** @batpad is there a way to do a one-time deletion of some of these problematic items? @elifitch suggested a database migration.

**Long-term solution:** @elifitch suggested that instead of creating deletion endpoints, we could instead add a `deleted` column to the database tables that defaults to `false`. When we want to "delete" a project or item, we set this value to `true`. The application middleware would be responsible for filtering out all `deleted: true` entries.

cc @samanpwbb @kepta

**Comment by batpad** [comment]
> Short-term solution: @batpad is there a way to do a one-time deletion of some of these problematic items? @elifitch suggested a database migration.

It's not so much of a problem to go into the database and muck around - BUT, I do think we should consider:

 - Setup a fresh stack with a fresh db - we probably want to do this eventually anyway.
 - Just ask item creators to create fresh projects for now

> Long-term solution: @elifitch suggested that instead of creating deletion endpoints, we could instead add a deleted column to the database tables that defaults to false. When we want to "delete" a project or item, we set this value to true. The application middleware would be responsible for filtering out all deleted: true entries.

Yes - this is exactly what the longer term solution should look like. I do think we will want this eventually, and probably sooner than later -- the cognitive burden on users having to filter out "test" or badly uploaded, etc. projects / items can be quite high, and it's nice to have a way to remove this visual clutter.

**Comment by batpad** [comment]
Let's prioritize this a bit.

Add an indexed boolean field called `is_archived` to projects and items. A `DELETE` operation on either sets this boolean to true. All queries for items and projects filter out everything where `is_archived=True`.

**Comment by batpad** [comment]
Thinking about this a bit more:

There seem to be a couple of different use-cases here, and they seem to be slightly different for `projects` and `items`:

 - For `projects`, it's mostly - this was a test project, or this project is no longer applicable - let's delete / hide it. For this, I think adding `is_archived` is the best solution as outlined above.

 - For `items`, it seems like there's possible a few different cases where one wants to hide or delete them:

  - Something like an erroneous upload of some items (eg. flipping lat-lng or so) -- you really just want to delete the items.
  - Indicating something like `this item is no longer valid` - eg. automatic linters that run everyday, and if an item has been fixed, it should no longer be part of the review queues. Here, I wonder if it makes more sense to set a `status` like `autoclosed` or something, not sure of the best naming. So, I think the options for items are:

     - Adding a field like `is_hidden` or `is_archived`
     - Having a `status` like `autoclosed` - linters / automatic processes then set this status when an item is no longer a problem / does not need to be reviewed.
     - Both.

I'm leaning toward doing both these on the `Item` level, and adding an `is_archived` which hides a project on the project level. I think having an additional status to know something was once flagged but has now been `autoclosed` by the automated process is useful to know, and to me, fits as another `status`.

Would like to hear thoughts, @samanpwbb @kepta @emilymdubois @oxidase @coxchapman

**Comment by coxchapman** [comment]
This is good, clear thinking @batpad! Agreed on the distinction on the different deletion needs between `projects` and `items`, and I think your solution is a sensible one.

**Comment by batpad** [comment]
This has been implemented on the back-end. Closing.
