### ISSUE TITLE
Change 'not fixable' to 'not actionable'

### ISSUE THREAD

**Issue by samanpwbb** [osmlab/to-fix-backend#226]
Change the status 'not fixable' to 'not actionable', which is a broader and more useful category.

**Comment by batpad** [comment]
hmm .. what do you want the backend to do here @samanpwbb ?

Add an additional status category like `notactionable` and `notactionable-verified` ?

**Comment by samanpwbb** [comment]
Honestly, we can just tweak the language on the frontend here.
