### ISSUE TITLE
Return limited data per item in `get-project-items` endpoint

### ISSUE THREAD

**Issue by batpad** [osmlab/to-fix-backend#234]
We should omit the `FeatureCollection` from the response in the `get-project-items` endpoint. A client should request for a single feature if they want the full representation, and the representation in the `list` view can be a `summary` representation.

cc @kepta - does that sound fine?

**Comment by kepta** [comment]
Currently the wait times are around sub minutes. This looks like a welcome addition to make tofix more usable. 

![screen shot 2017-11-13 at 9 03 47 am](https://user-images.githubusercontent.com/6966254/32708709-93a62016-c851-11e7-9385-e9e65b4783dc.png)
