### ISSUE TITLE
Fill in null values for /count_history

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix-backend#25]
![screen shot 2015-03-27 at 11 26 50 am](https://cloud.githubusercontent.com/assets/58878/6870716/2eee3f10-d474-11e4-81f5-8d7c7d000af3.png)

Gaps like this suck, there should be zeros in there.

**Comment by tristen** [comment]
Let's do this on the client. Closed with https://github.com/osmlab/to-fix/commit/8fc2439cc6d0b3cc603ab9114d0b222587b04005
