### ISSUE TITLE
Pass a "completed" message in the response header?

### ISSUE THREAD

**Issue by tristen** [osmlab/to-fix-backend#28]
If a task is complete, fetching for a new one results in a 404. It would be great to get something back that can tell us a task is currently complete for the day.

**Comment by aaronlidman** [comment]
Yeah, this should be handled a little more gracefully than it is now. I'll try and catch the error and see if it can respond with something more helpful.

**Comment by Rub21** [comment]
@tristen @aaronlidman : I did this issues: 

How is working: 
-  Created function  and new type data `item` in postgres

https://github.com/osmlab/to-fix-backend/blob/dev/lib/queries.js
- Replace lines:
- https://github.com/osmlab/to-fix-backend/blob/master/index.js#L225  by https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L228 

When we will create new task a  new function is will create as well.
on those lines
https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L401-407

#### Result

When the task is not complete the postgres function response  a  item like working now. 
but is the task is complete the data base response:
![image](https://cloud.githubusercontent.com/assets/1152236/8308649/959ec458-198b-11e5-9bfd-89e0a0714962.png)

`"complete";"{|skip|:|0|,|noterror|:|4|,|fix|:|6|,|total|:|10|}"`

we need to evaluate using `if` in those lines:
https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L232-243

The final response from server when task is complete is :

```
{
"key" : "complete"
"value" : {"skip":"0","noterror":"4","fix":"6","total":"10"}
}
```

Also I saw when a task is complete and someone click in button `skip`,`fix`,`not error`  the track is continue storing data like `""key"=>"", "user"=>"Rub21", "action"=>"skip""` with out any key. 
To avoid  this issue on server I added those lines
https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L71.

### To implement this in our alive server :
- We need to run function in DB and create  the new type data for our existing tasks ,it  can be easy.
- Run this new version of server.

**Comment by Rub21** [comment]
@tristen  Would be good after Aaron  check out the   solution of this issue , we can hit the https://github.com/osmlab/to-fix/issues/105,

**Comment by Rub21** [comment]
@aaronlidman @tristen : I did not about the error 410, I fixed the issue [according the hapi documentation](https://github.com/hapijs/boom#boomresourcegonemessage-data). 
https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L230-235

Now when a task is complete the server response 410 error and a object like : 

```
Object {statusCode: 410, error: "Gone", message: "{"key":"complete","value":{"skip":"6216","noterror":"1","fix":"57860","total":"60508"}}"}
```

**Comment by aaronlidman** [comment]
:+1:
