### ISSUE TITLE
Remember fixed items when updating

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix-backend#29]
After #6, we should remember which items have already been looked at by someone and prevent anyone from having to look at them again.

This will happen after table creation on CSV upload; some query between the new table and the previous stats table. As more tasks are completed this will become increasingly expensive.

It think this should only happen when swapping tasks, but if we can find a cheap way of doing it, it would be amazing to have it done globally on import. Blue sky, on import, check if it matches any of the previous millions of items looked at by someone and if it meets certain criteria (been looked at 3 times) remove it from the rotation.

**Comment by Rub21** [comment]
This won't be happening, close here!
