### ISSUE TITLE
Store task details

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix-backend#3]
We need a table to store details for each task.

Things like:
- titles
- descriptions
- time last updated
- auth settings (which users are allowed on the task, which user can modify settings)
- associated loader

These details would be used in building the UI, populating things like the sidebar and determining which loaders get used for a given task. This is all currently hard coded in the front end (index.js - see tasks var) and inflexible, requiring a commit for even minor changes.

**Comment by Rub21** [comment]
@aaronlidman , can you explain more about this issue. What things we need to do? if i know more about what things should we do i can jump here.

**Comment by aaronlidman** [comment]
@Rub21 When a user uploads a new task the details for the task name should go to a table just for tasks. This will replace https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json so we will also need a new API endpoint for retrieving these details.

**Comment by Rub21** [comment]
@aaronlidman  I'm thinking  on:

#### Storing Task details
- Create a table `task_details`

This should be contains :

```
  id character varying(100),
  title character varying(150),
  source character varying(150),
  owner character varying(150),
  description text,
  updated integer,
  status boolean

```
- Insert [tasks.json](https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json)  and create GET service to give us the task with `status=true`  Would be good also serve the task that have been completed. maybe it should be just  parameter. 
- Create a admin site in to-fix for **Add new task** , **Edit a task** .

Example:

![external sdcard-dcim-camera-img_20150713_112036 2](https://cloud.githubusercontent.com/assets/1152236/8654722/cbc5b930-2951-11e5-869c-24964f4acc21.jpg)
![external sdcard-dcim-camera-img_20150713_112244](https://cloud.githubusercontent.com/assets/1152236/8654723/cbc7d6a2-2951-11e5-99ea-b95782fa3aaf.jpg)

relative issues:
- https://github.com/osmlab/to-fix-backend/issues/3
- https://github.com/osmlab/to-fix-backend/issues/35

Would be much better if we make other page for this admins site in to-fix,  we need  to add more details  when we add new task, and also for look the details or status from one task  , using Login for users who  allow to add new task or edit the task.

**Edit task:** we have to work also in DB  and see the way to add more errors in same task:  from : https://github.com/osmlab/to-fix-backend/issues/6

**Comment by Rub21** [comment]
Progress Here : 
form to add more details of each task:

![add new3](https://cloud.githubusercontent.com/assets/1152236/8726818/172fe36c-2ba2-11e5-955e-3da6b34429b3.gif)

Show the detail of each task :

![details](https://cloud.githubusercontent.com/assets/1152236/8726876/5ef01208-2ba2-11e5-8c31-e4b61efe398e.gif)

**Comment by Rub21** [comment]
done!
