### ISSUE TITLE
How is working the tables on tofix DB?

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#37]
@aaronlidman 
I ran a server to check out how is working to-fix-backend.

I've loaded some csv files on server, I saw it create tables on data base is using  prefix `temp_`
![image](https://cloud.githubusercontent.com/assets/1152236/7854478/71d7ac28-0537-11e5-9a2d-6a590d34de4b.png)

but when I want to call those tasks 
https://github.com/osmlab/to-fix-backend/blob/master/index.js#L225
it give me error, the query that was executed is:
`UPDATE specialco x SET time=$1 FROM (SELECT key, time FROM specialco WHERE time < $2 AND time != 2147483647 ORDER BY time ASC LIMIT 1) AS sub WHERE x.key=sub.key RETURNING x.key, x.value;`

Is there something else to work after upload the files on backend? maybe change the name of tables? 

additional i am working in a new branch `dev` for   backend and frotend

**Comment by aaronlidman** [comment]
@Rub21 The `temp-*` table is created when the file is first uploaded. It is not supposed to stick around. You can see here: https://github.com/osmlab/to-fix-backend/blob/master/index.js#L342-L359 that another table is created from `temp-` and then `temp-` is dropped.
