### ISSUE TITLE
Update tofix-DB data from S3 files

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#44]
We need automatically update the tasks in to-fix.
**The workflow**

Detecting error in [OSMLint](https://github.com/osmlab/osmlint) -->[ Convert Json files to CSV ](https://github.com/osmlab/osmlint2csv)files readable by to-fix --> Update automatically the task using command line.

cc. @aaronlidman @lxbarth @maning

**Comment by aaronlidman** [comment]
@Rub21 - What about putting the files to a location on S3 and having to-fix pull them from there regularly?
- OSMLint -> convert json to csv -> s3
- to-fix backend downloads from s3 and loads into postgres

The file should only be loaded into postgres if it has changed from the day before.

This will remove the need for a human.

**Comment by Rub21** [comment]
@aaronlidman  it sounds fine :+1: , even much better.

Some Questions:
- how often should be updated to-fix  with the  s3 data? 
- how to to-fix knows when is time to update a task?, maybe is there any trigger from s3 when the file change?.
- Does the files should have the same name and rewrite when we other is uploading?

**Comment by aaronlidman** [comment]
> how often should be updated to-fix with the s3 data?

Can we check s3 for new data every hour?

> how to to-fix knows when is time to update a task?

Can it check every hour, and only load if the data is new? A [HEAD request](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) should be enough to check when the file was last modified.

> Does the files should have the same name and rewrite when we other is uploading?

That sounds ok

**Comment by Rub21** [comment]
Other way to update automatically is using lambda function!
