### ISSUE TITLE
Getting HTTP 500 when uploading sample file to the CSV endpoint

### ISSUE THREAD

**Issue by defvol** [osmlab/to-fix-backend#53]
I'm trying to follow the install script:

```
curl --form "file=@sample.csv" --form "password=$UploadPassword" --form "name=unconnectedmajor" http://localhost:8000/csv
```

On the last step I get an internal error.

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}%                                                               Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'replace' of undefined
    at Object.module.exports.csv (/Users/rodowi/c/to-fix-backend/src/post.js:105:30)

`data.id` is undefined here https://github.com/osmlab/to-fix-backend/blob/5e9f3fb8a331b4249b8bc5a41aa0f669757005a2/src/post.js#L104

**Comment by defvol** [comment]
Looks like if I pass `newtask=true` I should be able to get to the if statement where data.name is used instead of data.id

```
curl --form "file=@sample.csv" --form "password=$UploadPassword" --form "name=unconnectedmajor" --form "newtask=true" http://localhost:8000/csv
```

{"statusCode":400,"error":"Bad Request","message":"error: INSERT has more expressions than target columns"}

Still getting an error

But the second time I get a message indicating that the task already exists, or something like that:

{"statusCode":400,"error":"Bad Request","message":"error: relation \"unconnectedmajor_stats\" already exists"}

**Comment by Rub21** [comment]
@rodowi  : This issue could be fixed in the next version of to-fix.

**Comment by Rub21** [comment]
close here!!
