### ISSUE TITLE
Updating to-fix-backend 

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#54]
These weeks we are trying to improve to-fix-backed,  there are big changes since we have to change the [geojson support](https://github.com/osmlab/to-fix-backend/issues/49), and also to handle the tasks through projects(per chat and voice w/ Aaron), the changes is happening in [this branch](https://github.com/osmlab/to-fix-backend/tree/devrub21). and also we are enhancing many functionalities.

cc. @aaronlidman @rodowi @mikelmaron @batpad @geohacker @planemad @maning @ajithranka

**Comment by aaronlidman** [comment]
I'm starting this for two days before handing off. See you in a few.

**Comment by Rub21** [comment]
This is happening here https://github.com/osmlab/to-fix-backend/pull/58
