### ISSUE TITLE
Endpoint testing

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#55]
All endpoint should be tested. 

cc. @rodowi @aaronlidman

**Comment by defvol** [comment]
a couple of ideas for testing the API
- [tape](https://www.npmjs.com/package/tape) for simple assertion
- I've been using [nock](https://www.npmjs.com/package/nock) lately, which is great for stubbing HTTP response from any server.

**Comment by defvol** [comment]
Actually, [supertest](https://www.npmjs.com/package/supertest) seems to be a better option, as it comes w expectation helpers and a http client.

**Comment by defvol** [comment]
so supertest didn't work for HAPI, let's try https://www.npmjs.com/package/superagent

**Comment by defvol** [comment]
See #62 
Using server.inject to test endpoints

**Comment by Rub21** [comment]
We are ready here!!

**Comment by defvol** [comment]
Closed by https://github.com/osmlab/to-fix-backend/pull/62
