### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by defvol** [osmlab/to-fix-backend#56]
To make it easier for new contributors to jump in, we should define a coding style and enforce it with linters, such as http://eslint.org

**Comment by Rub21** [comment]
@rodowi ,  the code is using [.eslintrc](https://github.com/osmlab/to-fix-backend/blob/656e96251dfee922d111f047738a4276317b9266/.eslintrc)  to run it  only we need run `npm run lint`

**Comment by defvol** [comment]
Ok, eslint was added on Sep 6. Closing...

**Comment by defvol** [comment]
Thanks @Rub21 !
