### ISSUE TITLE
Swap task data

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix-backend#6]
It's currently not possible to set up a task and then replace the data. There should be a way of swapping an existing table with a temp table with no downtime.

Not sure how this would work but right now the only way is to log in, delete the old table, and create a new one with the same name. Which isn't ideal.

**Comment by aaronlidman** [comment]
This brings up some interesting issues, especially around tracking.
- Do we preserve the stats table?
  - Make it optional right? Default is to keep stats, with the possibility to archive it.
- How do we archive old tasks?
  - Keep a table around? pg_dump? Do we even bother?

Basically, how transient is this data? How much should we care about persisting some semblance of state and being able to look up everything in the past? As the task gets completed, stats become more important than the task data originally provided. How do we archive that in a way that we can still use in the past, but not block new tasks or clutter a UI? I might be over thinking this. ;)

**Comment by Rub21** [comment]
I fixed this issue, now more easy to update a task!
