### ISSUE TITLE
Wrong current issues number

### ISSUE THREAD

**Issue by samely** [osmlab/to-fix-backend#63]
@Rub21 
Current issues number in tasks such as Strange layer are not being shown correctly: 
 ![image](https://cloud.githubusercontent.com/assets/10425629/20759197/3268da1a-b6ea-11e6-8ec6-e525a278346f.png)
*No more issues*

![image](https://cloud.githubusercontent.com/assets/10425629/20759170/208b2668-b6ea-11e6-8826-f2a703485a15.png)
*Still 1,963 issues*

And of course, this task is not in the **Completed tasks** part

@ajithranka @aaronlidman

**Comment by ajithranka** [comment]
The task summary shows that the task currently has 1963 items when no items exist. Fetching the items returns a empty array.

<img width="762" alt="screen shot 2016-11-30 at 9 03 02 pm" src="https://cloud.githubusercontent.com/assets/11095038/20760605/7d4f6894-b746-11e6-91a9-e9fb35e7033c.png">
<img width="763" alt="screen shot 2016-11-30 at 9 00 28 pm" src="https://cloud.githubusercontent.com/assets/11095038/20760606/7d925ea6-b746-11e6-9cd2-a405eb89890e.png">

**Comment by ajithranka** [comment]
@rodowi Do you have an idea why this might be happening? I'm not familiar with the backend code.

**Comment by Rub21** [comment]
the error is when the task is  updating with empty geojson files, empty  geojson files  is when there are no any detection by osmlint.

I've fixed this and deployed

**Comment by defvol** [comment]
@Rub21 mind sharing a link to the commit that fixed this?

**Comment by Rub21** [comment]
@rodowi here: https://github.com/osmlab/to-fix-backend/commit/a39144ddde747a740baf3cb7b6f77a9cdcccbca2
