### ISSUE TITLE
update a task which has a lot items is failing 

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#71]
cc. @ajithranka

**Comment by ajithranka** [comment]
:-/ 

@Rub21 Do you know how many features we can safely support right now?

**Comment by Rub21** [comment]
@ajithranka , to create a task, I tested with more than 500,000 item, it works fine, the problem when we want to update it. the problem is here https://github.com/osmlab/to-fix-backend/blob/master/src/controllers/ControllerTasks.js#L247-L292, I am working on that, maybe the URL for getting an item could change a little bit.

**Comment by Rub21** [comment]
to resolve the problem and, and give and option for this https://github.com/osmlab/to-fix/issues/173, I made some changes in the items from-end  
![image](https://cloud.githubusercontent.com/assets/1152236/22079184/e5d1fdc4-dd88-11e6-8cea-9c29e6edc733.png).

`type` will come from the stats, we already have the branch https://github.com/osmlab/to-fix-backend/tree/fixupdate,I think we can run this improvement after run `auth`
```
{
  "tasks": [
    {
      "idtask": "tigerdeltanrpsq",
      "isCompleted": false,
      "isAllItemsLoad": true,
      "iduser": "510836",
      "value": {
        "name": "Tiger delta",
        "description": "Detection of tiger delta for main cities in the United States",
        "updated": 1484755582,
        "changesetComment": "Aligning or naming imported tiger roads #to-fix",
        "stats": {
          "edit": 0,
          "fixed": 0,
          "noterror": 0,
          "skip": 0,
          "type": "saolctvpjjmsmih",
          "date": 1484755582,
          "items": 356
        }
      }
    },
    {
      "idtask": "tigerdeltadjts",
      "isCompleted": false,
      "isAllItemsLoad": true,
      "iduser": "510836",
      "value": {
        "name": "Tiger delta",
        "description": "Detection of tiger delta for main cities in the United States",
        "updated": 1484756214,
        "changesetComment": "Aligning or naming imported tiger roads #to-fix",
        "stats": {
          "edit": 0,
          "fixed": 0,
          "noterror": 0,
          "skip": 0,
          "type": "pcbpnreuhbolvi",
          "date": 1484756214,
          "items": 356
        }
      }
    }]
}

**Comment by Rub21** [comment]
done!!
