### ISSUE TITLE
Algo va mal con las tareas de unconnected

### ISSUE THREAD

**Issue by samely** [osmlab/to-fix-backend#76]
@Rub21 
He estado trabajando en unconnected, pero es una tarea de nunca terminar. 
Según las estadísticas aún hay tareas, pero no hay más items ni en web ni en el plugin.

![image](https://cloud.githubusercontent.com/assets/10425629/22486838/1e19ac68-e7d9-11e6-8900-9b9388fc2410.png)
*La tarea no pasa a tareas finalizadas*
![image](https://cloud.githubusercontent.com/assets/10425629/22486860/38be546a-e7d9-11e6-9f3b-3021e2679c03.png)
*Vista de acceso a la tarea vía web*

**Comment by Rub21** [comment]
El error fue cuando un archivo geojson  contiene elementos duplicados, to-fix-backend solo sube elemetos no publicado. y tambien una err OSMLint que ya fue solucionado  [aqui](https://github.com/osmlab/osmlint/commit/5e62c45d4fc609c3ed0a90f19b38b56fa6bc3e94) y tambien se agrego filtros para evitar items repetidos en to-ix-backend
