### ISSUE TITLE
Creating projects in to-fix

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#81]
Our next actions for adding more functionalities in  To-fix, is created projects and under this, we can create many tasks as we want.

The next list is the play which I want to work the coming days.

- The admin user can create a  project
- The projects can be public or private.
- The owner of the project can create any task as they want under this project. 
- Adding a list of user to see this particular project.

any other thoughts? 

cc. @geohacker @batpad @ajithranka @amishas157 @rodowi @aaronlidman

**Comment by ajithranka** [comment]
@Rub21 This sounds great! Are you planning to add projects as part of the [version 1](https://github.com/osmlab/to-fix/issues/176) release? We should scope out the changes and decide if it will be a lift.

**Comment by geohacker** [comment]
@Rub21 I'm a bit confused what a `project` is. Could you help me understand with an example? What would be a project? What are the tasks in the project? How will this help our workflows?

**Comment by Rub21** [comment]
> @Rub21 I'm a bit confused what a project is. Could you help me understand with an example? What would be a project? What are the tasks in the project? How will this help our workflows?

Per conversation with @geohacker , all the above stuff was clarified!!!

**Comment by kepta** [comment]
Closing this in favour of the  postgis rewrite #113
