### ISSUE TITLE
Timeout error when fetching items

### ISSUE THREAD

**Issue by ajithranka** [osmlab/to-fix-backend#83]
This happens sometimes when trying to fetch items in a task.

![screen shot 2017-03-09 at 09 51 06](https://cloud.githubusercontent.com/assets/11095038/23790365/c9f59586-05a4-11e7-966e-b5dc587458d8.png)

cc: @Rub21 @geohacker

**Comment by Rub21** [comment]
This happened when  I accumulate the stats in the same task,  this should be fixed since we are storing the stats in other `type`.
