### ISSUE TITLE
Problemas al cargar la data en TOFIX

### ISSUE THREAD

**Issue by piligab** [osmlab/to-fix-backend#90]
Según el reporte de OSMLint en la tarea de [Island Minor](https://gist.github.com/anonymous/27ae2272fd22a331e615f49ac7dfdeb6), aparece un total de 621 errores detectados.

![image](https://cloud.githubusercontent.com/assets/19536044/25155390/6f254f50-245a-11e7-8907-34cd6bef0958.png)

Pero toda esta data no se está cargando en TOFIX.

cc. @Rub21

**Comment by Rub21** [comment]
@piligab  I've  fixed this issues, close  here!!
