### ISSUE TITLE
Problems loading the data into the Strange layer TOFIX task

### ISSUE THREAD

**Issue by luiswalter** [osmlab/to-fix-backend#95]
According to the OSMLint report in the taks [Strange Layer](https://osmlab.github.io/to-fix/#/stats/strangelayer), a total of 321 errors are detected. 
![strange](https://cloud.githubusercontent.com/assets/17984615/25725483/cff9cc56-30e5-11e7-91a9-9ca3d9a6b1ca.png)

But all this data is not being loaded into TOFIX.

@Rub21

**Comment by Rub21** [comment]
fixed : https://osmlab.github.io/to-fix/#/task/strangelayer
