### ISSUE TITLE
Login fails on to-fix frontend

### ISSUE THREAD

**Issue by ajithranka** [osmlab/to-fix-backend#96]
<img width="617" alt="screen shot 2017-05-22 at 5 25 31 pm" src="https://cloud.githubusercontent.com/assets/11095038/26307779/ee405d38-3f13-11e7-8601-dae5321e8e29.png">

@Rub21 do you mind checking if this is a backend issue?

cc: @batpad

**Comment by Rub21** [comment]
Fixed here https://github.com/osmlab/to-fix-backend/pull/97

**Comment by ajithranka** [comment]
The login works on the front-end now. Thank you @Rub21!
