### ISSUE TITLE
Error when I logged

### ISSUE THREAD

**Issue by dannykath** [osmlab/to-fix-backend#98]
@Rub21  I can not access the page https://osmlab.github.io/to-fix/#/task/brokenpolygons 

![tofix](https://cloud.githubusercontent.com/assets/8483644/26794560/b69c793c-49e7-11e7-9e86-c7d6547df2d7.png)

![log](https://cloud.githubusercontent.com/assets/8483644/26794568/be149654-49e7-11e7-8422-09588468d4d9.png)

![3](https://cloud.githubusercontent.com/assets/8483644/26794571/c37529e2-49e7-11e7-8750-92cbeed98bad.png)

Could you please check it ?

**Comment by Rub21** [comment]
@dannykath creo que es porque el API de osm estaba de baja, uedes probar nuevamente.
